// <auto-generated />
using System;
using BlazoeProject.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazoeProject.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("BlazoeProject.Shared.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finace"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Devops"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vas IOT"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Busines"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Medical"
                        });
                });

            modelBuilder.Entity("BlazoeProject.Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "mukhwami@gmail.com",
                            FirstName = "ombasa",
                            Gender = 0,
                            LastName = "mukhwami",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "martin.simiyu@test.com",
                            FirstName = "martin",
                            Gender = 0,
                            LastName = "simiyu",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2002, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "joel.orandi@tes.com",
                            FirstName = "joel",
                            Gender = 0,
                            LastName = "orangi",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2001, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "ososi.vincent@tes.com",
                            FirstName = "ososi",
                            Gender = 0,
                            LastName = "vincent",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "phelisters.bogonko@test.com",
                            FirstName = "phelisters",
                            Gender = 1,
                            LastName = "Bogongo",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1998, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "silas.mogare@test.com",
                            FirstName = "silas",
                            Gender = 0,
                            LastName = "mogare",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2009, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            Email = "scholastica.memusi@test.com",
                            FirstName = "scholastica",
                            Gender = 1,
                            LastName = "memusi",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2002, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            Email = "breana62@gmail.com",
                            FirstName = "branambo",
                            Gender = 1,
                            LastName = "midecha",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2006, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            Email = "sarah.moraa@test.com",
                            FirstName = "sarah",
                            Gender = 1,
                            LastName = "moraa",
                            PhotoPath = "images/john.png"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2004, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            Email = "aquirinah.mukhwami@test.com",
                            FirstName = "Aquirinah",
                            Gender = 1,
                            LastName = "mukhwami",
                            PhotoPath = "images/john.png"
                        });
                });

            modelBuilder.Entity("BlazoeProject.Shared.Employee", b =>
                {
                    b.HasOne("BlazoeProject.Shared.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
